apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
  - port: 8080
    name: server
  selector:
    app: server
  type: LoadBalancer
  sessionAffinity: ClientIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 2
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: youtube-downloader-server
        image: youtube-downloader-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: LOG_LEVEL
          value: debug
        - name: RABBIT_HOST
          value: rabbitmq-rabbitmq
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: user
        - name: RABBIT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-rabbitmq
              key: rabbitmq-password
