app:
  build: .
  ports:
    - 8080:8080
  environment:
    - LOG_LEVEL=debug
    - HOST=0.0.0.0
    - PORT=8080
    - RABBIT_HOST=rabbitmq
  links:
    - rabbitmq

rabbitmq:
  image: rabbitmq:3-management
  ports:
    - 15672:15672
    - 5672:5672
